apiVersion: v2
name: cnpg-cluster
description: Deploys and manages a CloudNativePG cluster and its associated resources.
type: application
version: 1.0.0
sources:
  - https://github.com/re0udjat/homelab/apps/cloudnative-pg/cluster
keywords:
  - postgresql
  - postgres
  - database
maintainers:
  - name: cuongnlt
    email: cuongnguyenletuan@gmail.com