apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{  include "cluster.fullname" . }}
  namespace: {{ .Release.Namespace }}
  {{- with .Values.cluster.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
  {{- include "cluster.labels" . | nindent 4 }}
  {{- with .Values.cluster.additionalLabels }}
    {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  instances: {{ .Values.cluster.instances }}
  {{- include "cluster.image" . | nindent 2 }}
  imagePullPolicy: {{ default "IfNotPresent" .Values.cluster.imagePullPolicy }}
  storage:
    size: 1Gi